#!/bin/bash
IFS=$'\n'
BROKEN=`rtcontrol --from-view main \* -qo hash is_complete=no`
for hash in $BROKEN; do
  echo $hash
  rm -v /home/seeder1/rtorrent/.session/"$hash".torrent.libtorrent_resume
done

