#!/bin/bash
IFS=$'\n'

source $HOME/transcode.conf

torrentcount=0
for torrent in $(find "${transcodefolder}" -maxdepth 1 -name "*.torrent" 2>/dev/null); do
  echo "Processing: ${torrent}"
  ((torrentcount++))
  torrent_hash=$(/usr/local/bin/lstor "${torrent}" -qo __hash__)
  # copy to watch folder
  mv "${torrent}" "${watchfolder}"
  # wait for rtorrent to register the torrent
  until [ "$(/usr/local/bin/rtcontrol -qo name hash=${torrent_hash} | wc -l)" -eq "1" ]; do
    echo "Waiting for torrent to be registered..."
    sleep 5
  done
  echo "Labelling torrent..."
  /usr/local/bin/rtcontrol -qo name hash=${torrent_hash} --custom=1="tc"
  echo "Done."
done
if [[ "${torrentcount}" == "0" ]]; then
  echo "No torrents to process."
fi

