#!/bin/bash

TORRENTDIR="/home/seeder1/rtorrent/transtorrent/"
WATCHFOLDER="/home/seeder1/rtorrent/watch/"

for torrent in "$TORRENTDIR"*.torrent; do
  echo "Processing: $torrent"
  torrent_hash=`lstor "$torrent" -qo __hash__`
  # copy to watch folder
  mv "$torrent" "$WATCHFOLDER"
  # wait for rtorrent to register the torrent
  until [ "$(rtcontrol -qo name hash=$torrent_hash | wc -l)" -eq "1" ]; do
    echo "Waiting for torrent to be registered..."
    sleep 10
  done
  echo "Labelling torrent..."
  rtcontrol -qo name hash=$torrent_hash --custom=1="tc"
  echo "Done."
done
