#!/bin/bash
IFS=$'\n'

source $HOME/transcode.conf

cron=false

foldername=''
arg=''
rtinfo=''
hash=''

if [[ "$#" == 1 && "$1" == -* ]]; then
    echo "Folder Name is Required.  Exiting..."
    exit
else
    foldername="$1"
fi

if [[ "$#" == 2 ]]; then
    arg="$1"
    rtinfo="$2"
    if [[ -n "${rtinfo}" ]]; then
      # note trailing slash here is critical
      foldername=$(echo "${rtinfo}" | cut -f1)/
      hash=$(echo "${rtinfo}" | cut -f2)
    else
      echo "No matching torrents.  Exiting..."
      exit
    fi
fi

case "${arg}" in
    -cron) cron=true ;;
    *) #future use
      ;;
esac

if [[ -z "${foldername}" || ! -d "${downloads}${foldername}" ]]; then
    echo "No matching torrents.  Exiting..."
    exit
fi

musicfoldercount=0
artfoldercount=0
declare -a musicfolders
declare -a artfolders
subfoldercount=$(find "${downloads}${foldername}"*/ -maxdepth 1 -type d -print 2>/dev/null | wc -l)
if [[ "${subfoldercount}" > "0" ]]; then
  subfolderlist=''
  allsubfolderlist=$(find "${downloads}${foldername}"*/ -maxdepth 1 -type d -printf "%f\n")
  # add '.' for parent folder
  allsubfolderlist="${allsubfolderlist}"$'\n'
  echo -e "${allsubfolderlist}x"
  while read -r subfoldername; do
    musicfilecount=$(find "${downloads}${foldername}${subfoldername}" -maxdepth 1 -name "*.flac" | wc -l)
    echo "subfolder: $downloads$foldername$subfoldername - musicfilecount: ${musicfilecount}"
    if [[ "${musicfilecount}" > "0" ]]; then
      echo "this: ${subfoldername}"
      musicfolders[musicfoldercount]="${subfoldername}"
      ((musicfoldercount++))
    elif [ -n "${subfoldername}" ]; then
      # if the name is not blank (parent) then we assume it's art
      artfolders[artfoldercount]="${subfoldername}"
      ((artfoldercount++))
    fi
  done <<< "${allsubfolderlist}"
else
  musicfolders[0]=''
fi
# Various Artists?
counter=0
various=false
for flacfile in $(find "${downloads}${foldername}${musicfolders[0]}" -maxdepth 1 -type f -name "*.flac" 2>/dev/null); do
  thisartist="$(metaflac --show-tag=ARTIST "${flacfile}" | sed -n -e 's/^ARTIST=//pI' | sed -r 's/[:,?<>*|/]+/-/g')"
  if [[ "${counter}" == "0" ]]; then
    firstflacfile="${flacfile}"
    firstfileartist="${thisartist}"
  else
    if [[ "${firstfileartist}" != "${thisartist}" ]]; then
      various=true
      break
    fi
  fi
  (( counter++ ))
done
if ${various}; then
    artist="Various Artists"
else
    artist="${firstfileartist}"
fi
album=$(metaflac --show-tag=ALBUM "${firstflacfile}" | sed -n -e 's/^ALBUM=//pI' | sed -r 's/[:,?<>*|/]+/-/g')
year=$(metaflac --show-tag=DATE "${firstflacfile}" | sed -n -e 's/^DATE=//pI')
newfolder="$artist - $album ($year) [V0]/"
if ! "${cron}"; then
    echo "${newfolder}"
    read -p "Use this folder name? " -n 1 -r
    if ! [[ "${REPLY}" =~ ^[yY]$ ]]; then
        echo
        read -p "Enter the desired folder name: "
        newfolder="$REPLY"
        echo "$newfolder"
        read -p "Use this folder name? " -n 1 -r
        if [[ "${REPLY}" =~ ^[yY]$ ]]; then
          good=true
        fi
    else
        good=true
    fi
    echo
    case "${newfolder}" in
        */) # do nothing
            ;;
        *) newfolder="$newfolder/";;
    esac
else
    # this is cron job
    if [[ -n "${artist}" && -n "${album}" && -n "${year}" ]]; then
        good=true
        /usr/local/bin/rtcontrol --from-view main \* -qo name hash=${hash} --custom=1="tc_processing"
    else
        echo "Bad or no tags"
        /usr/local/bin/rtcontrol --from-view main \* -qo name hash=${hash} --custom=1="tc_failed"
        subject="Transcode Failed - ${foldername}"
        mail="subject:${subject}\nfrom:${from}\nThe title says it all, but Google wants more, so here is some more text.  This folder could not be transcoded  -Your Friend, Sterns"
        echo -e "$mail" | /usr/sbin/sendmail "$recipients"
        exit
    fi
fi
if ${good}; then
    while read -r subfoldername; do
      mkdir -p "${downloads}${newfolder}${subfoldername}"
      parallel -j${maxthreads} avconv -i {} -codec:v copy -qscale:a 0 {.}.mp3 ::: "${downloads}${foldername}${subfoldername}"*.flac
      mv "${downloads}${foldername}${subfoldername}"*.mp3 "${downloads}${newfolder}${subfoldername}"
      cp "${downloads}${foldername}${subfoldername}"*.{jpg,png,log,txt} "${downloads}${newfolder}${subfoldername}"
      echo "Finished Transcoding Folder."
    done <<< "${musicfolders[*]}"
    if [[ "${artfoldercount}" > "0" ]]; then
      while read -r artfolder; do
        cp -r "${downloads}${foldername}${artfolder}" "${downloads}${newfolder}"
      done <<< "${artfolders[*]}"
    fi
    echo "Start Torrent Creation..."
    "${binfolder}"/py3createtorrent.py -P "${downloads}${newfolder}" what -o /home/seeder1/rtorrent/newtorrent/
    newtorrent="${newfolder%/}".torrent
    cp "/home/seeder1/rtorrent/newtorrent/${newtorrent}" "${watchfolder}"
    "${binfolder}"/rtcontrol --from-view main \* -qo name hash=${hash} --custom=1=""
    subject="Transcode Completed - ${foldername}"
    mail="subject:${subject}\nfrom:${from}\nThe title says it all, but Google wants more, so here is some more text.\n \
      https://what.cd/torrents.php?groupname=${hash}"
    echo -e "${mail}" | /usr/sbin/sendmail "${recipients}"
else
    echo
    echo "Aborted!"
    echo
fi
