#!/bin/bash
IFS=$'\n'

source $HOME/transcode.conf

cron=false

foldername=''
arg=''
rtinfo=''
hash=''

if [[ "$#" == 1 && "$1" == -* ]]; then
    echo "Folder Name is Required.  Exiting..."
    exit
else
    foldername="$1"
fi

if [[ "$#" == 2 ]]; then
    arg="$1"
    rtinfo="$2"
    if [[ -n "${rtinfo}" ]]; then
      # note trailing slash here is critical
      foldername=$(echo "${rtinfo}" | cut -f1)/
      hash=$(echo "${rtinfo}" | cut -f2)
    else
      echo "No matching torrents.  Exiting..."
      exit
    fi
fi

case "${arg}" in
    -cron) cron=true ;;
    *) #future use
      ;;
esac

if [[ -z "${foldername}" || ! -d "${downloads}${foldername}" ]]; then
    echo "No matching torrents.  Exiting..."
    exit
fi

musicfoldercount=0
echo "here a"
subfoldercount=$(find "${downloads}${foldername}"*/ -maxdepth 1 -type d -print | wc -l)
echo "done a: subfoldercount: ${subfoldercount}"
if [[ "${subfoldercount}" > "0" ]]; then
  subfolderlist=''
  allsubfolderlist=$(find "${downloads}${foldername}"*/ -maxdepth 1 -type d -printf "%f\n")
  for subfoldername in "$allsubfolderlist"; do
    musicfilecount=$(find "${downloads}${foldername}${subfoldername}" -name *.flac | wc -l)
    if [[ "${musicfilecount}" > "0" ]]; then
      ((musicfoldercount++))
      subfolderlist="${subfolderlist}${subfoldername}"$'\n'
    fi
  done
  if [[ "${musicfoldercount}" > "0" ]]; then
    firstsubfoldername=$(echo "${subfolderlist}" | head -1)
  fi
else
  firstsubfoldername=''
fi
firstflacfile=$(ls "${downloads}${foldername}${firstsubfoldername}" | grep -i -E '\.flac$' | head -1)
secondflacfile=$(ls "${downloads}${foldername}${firstsubfoldername}" | grep -i -E '\.flac$' | head -2 | tail -1)
artist1=$(metaflac --show-tag=ARTIST "${downloads}${foldername}${firstsubfoldername}$firstflacfile" | sed -n -e 's/^ARTIST=//pI' | sed -r 's/[:,?<>*|/]+/-/g')
artist2=$(metaflac --show-tag=ARTIST "${downloads}${foldername}${firstsubfoldername}$secondflacfile" | sed -n -e 's/^ARTIST=//pI' | sed -r 's/[:,?<>*|/]+/-/g')
if [ "$artist1" == "$artist2" ]; then
    artist="$artist1"
else
    artist="Various Artists"
fi
album=$(metaflac --show-tag=ALBUM "${downloads}${foldername}${firstsubfoldername}${firstflacfile}" | sed -n -e 's/^ALBUM=//pI' | sed -r 's/[:,?<>*|/]+/-/g')
year=$(metaflac --show-tag=DATE "${downloads}${foldername}${firstsubfoldername}${firstflacfile}" | sed -n -e 's/^DATE=//pI')
newfolder="$artist - $album ($year) [V0]/"
good=false
if ! "$cron" ; then
    echo "$newfolder"
    read -p "Use this folder name? " -n 1 -r
    if ! [[ "${REPLY}" =~ ^[yY]$ ]]; then
        echo
        read -p "Enter the desired folder name: "
        newfolder="$REPLY"
        echo "$newfolder"
        read -p "Use this folder name? " -n 1 -r
        if [[ "$REPLY" =~ ^[yY]$ ]]; then
          good=true
        fi
    else
        good=true
    fi
    case "$newfolder" in
        */) # do nothing
            ;;
        *) newfolder="$newfolder/";;
    esac
else
    # this is cron job
    if [[ -n "$artist" && -n "$album" && -n "$year" ]]; then
        good=true
        /home/seeder1/bin/rtcontrol --from-view main \* -qo name hash=${hash} --custom=1="tc_processing"
    else
        echo "Bad or no tags"
        /home/seeder1/bin/rtcontrol --from-view main \* -qo name hash=${hash} --custom=1="tc_failed"
        subject="Transcode Failed - ${foldername}"
        mail="subject:${subject}\nfrom:${from}\nThe title says it all, but Google wants more, so here is some more text.  This folder could not be transcoded  -Your Friend, Sterns"
        echo -e "$mail" | /usr/sbin/sendmail "$recipients"
        exit
    fi
fi
if ${good}; then
    if [[ "${musicfoldercount}" == "0" ]]; then
        echo
        echo "Great!  Transcoding..."
        mkdir "${downloads}${newfolder}"
        parallel -j${maxthreads} avconv -i {} -qscale:a 0 {.}.mp3 ::: "${downloads}${foldername}"*.flac
        mv "${downloads}${foldername}"*.{mp3,jpg,png,log,txt} "${downloads}${newfolder}"
        echo "Finished Transcoding."
    else
        for subfoldername in "$subfolderlist"; do
            mkdir -p "${downloads}${newfolder}${subfoldername}"
            parallel -j${maxthreads} avconv -i {} -qscale:a 0 {.}.mp3 ::: "${downloads}${foldername}${subfoldername}"*.flac
            mv "${downloads}${foldername}${subfoldername}"*.{mp3,jpg,png,log,txt} "${downloads}${newfolder}${subfoldername}"
            echo "Finished Transcoding."
        done
    fi

    echo "Start Torrent Creation..."
    /usr/local/bin/py3createtorrent.py -P "${downloads}${newfolder}" what -o /home/seeder1/rtorrent/newtorrent/
    newtorrent="${newfolder%/}".torrent
    cp "/home/seeder1/rtorrent/newtorrent/${newtorrent}" /home/seeder1/rtorrent/watch/
    /home/seeder1/bin/rtcontrol --from-view main \* -qo name hash=${hash} --custom=1=""
    subject="Transcode Completed - ${foldername}"
    mail="subject:${subject}\nfrom:${from}\nThe title says it all, but Google wants more, so here is some more text."
    echo -e "${mail}" | /usr/sbin/sendmail "${recipients}"
else
    echo
    echo "Aborted!"
    echo
fi
