#!/bin/bash
mkdir resampled # make a subdirectory to put our files in
parallel -j8 sox -S "{}" -r 44100 -b 16 "resampled/{}" ::: *.flac
cp "*.{mp3,jpg,png,log,txt}" "resampled/"
echo "Finished Transcoding."

